export const UNITS = [
  "g", "kg", "ml", "cl", "L",
  "c. à soupe", "c. à café",
  "pièce", "tranche", "feuille", "gousse",
  "pincée", "sachet", "boîte", "verre",
  "branche", "bouquet", "poignée",
];

export type IngredientSuggestion = { name: string; unit: string };

export const INGREDIENT_SUGGESTIONS: IngredientSuggestion[] = [
  // Viandes
  { name: "Poulet", unit: "g" },
  { name: "Blanc de poulet", unit: "g" },
  { name: "Cuisse de poulet", unit: "pièce" },
  { name: "Dinde", unit: "g" },
  { name: "Bœuf haché", unit: "g" },
  { name: "Steak", unit: "pièce" },
  { name: "Côte de porc", unit: "pièce" },
  { name: "Lardons", unit: "g" },
  { name: "Jambon", unit: "tranche" },
  { name: "Bacon", unit: "tranche" },
  { name: "Saucisse", unit: "pièce" },
  { name: "Merguez", unit: "pièce" },
  { name: "Agneau", unit: "g" },
  { name: "Veau", unit: "g" },
  { name: "Canard", unit: "g" },
  // Poissons & fruits de mer
  { name: "Saumon", unit: "g" },
  { name: "Thon", unit: "boîte" },
  { name: "Cabillaud", unit: "g" },
  { name: "Crevettes", unit: "g" },
  { name: "Moules", unit: "g" },
  { name: "Sardines", unit: "boîte" },
  { name: "Daurade", unit: "pièce" },
  // Légumes
  { name: "Tomate", unit: "pièce" },
  { name: "Carotte", unit: "pièce" },
  { name: "Oignon", unit: "pièce" },
  { name: "Ail", unit: "gousse" },
  { name: "Courgette", unit: "pièce" },
  { name: "Aubergine", unit: "pièce" },
  { name: "Poivron", unit: "pièce" },
  { name: "Pomme de terre", unit: "pièce" },
  { name: "Patate douce", unit: "pièce" },
  { name: "Épinards", unit: "g" },
  { name: "Champignons", unit: "g" },
  { name: "Poireau", unit: "pièce" },
  { name: "Brocoli", unit: "pièce" },
  { name: "Chou-fleur", unit: "pièce" },
  { name: "Haricots verts", unit: "g" },
  { name: "Petits pois", unit: "g" },
  { name: "Laitue", unit: "pièce" },
  { name: "Roquette", unit: "g" },
  { name: "Concombre", unit: "pièce" },
  { name: "Avocat", unit: "pièce" },
  { name: "Céleri", unit: "branche" },
  { name: "Fenouil", unit: "pièce" },
  { name: "Radis", unit: "bouquet" },
  { name: "Betterave", unit: "pièce" },
  // Féculents
  { name: "Pâtes", unit: "g" },
  { name: "Spaghetti", unit: "g" },
  { name: "Penne", unit: "g" },
  { name: "Tagliatelle", unit: "g" },
  { name: "Riz", unit: "g" },
  { name: "Quinoa", unit: "g" },
  { name: "Lentilles", unit: "g" },
  { name: "Pois chiches", unit: "g" },
  { name: "Farine", unit: "g" },
  { name: "Pain", unit: "tranche" },
  { name: "Semoule", unit: "g" },
  { name: "Couscous", unit: "g" },
  { name: "Boulgour", unit: "g" },
  // Produits laitiers & œufs
  { name: "Lait", unit: "ml" },
  { name: "Crème fraîche", unit: "g" },
  { name: "Crème liquide", unit: "cl" },
  { name: "Beurre", unit: "g" },
  { name: "Huile d'olive", unit: "c. à soupe" },
  { name: "Huile", unit: "c. à soupe" },
  { name: "Parmesan", unit: "g" },
  { name: "Gruyère", unit: "g" },
  { name: "Emmental", unit: "g" },
  { name: "Mozzarella", unit: "g" },
  { name: "Feta", unit: "g" },
  { name: "Chèvre", unit: "g" },
  { name: "Yaourt", unit: "pièce" },
  { name: "Œuf", unit: "pièce" },
  { name: "Œufs", unit: "pièce" },
  // Condiments & épices
  { name: "Sel", unit: "pincée" },
  { name: "Poivre", unit: "pincée" },
  { name: "Sucre", unit: "g" },
  { name: "Miel", unit: "c. à soupe" },
  { name: "Moutarde", unit: "c. à soupe" },
  { name: "Vinaigre", unit: "c. à soupe" },
  { name: "Sauce soja", unit: "c. à soupe" },
  { name: "Concentré de tomate", unit: "c. à soupe" },
  { name: "Tomates pelées", unit: "boîte" },
  { name: "Bouillon de poulet", unit: "sachet" },
  { name: "Bouillon de légumes", unit: "sachet" },
  { name: "Cumin", unit: "c. à café" },
  { name: "Paprika", unit: "c. à café" },
  { name: "Curry", unit: "c. à café" },
  { name: "Curcuma", unit: "c. à café" },
  { name: "Cannelle", unit: "c. à café" },
  { name: "Thym", unit: "branche" },
  { name: "Romarin", unit: "branche" },
  { name: "Basilic", unit: "feuille" },
  { name: "Persil", unit: "bouquet" },
  { name: "Coriandre", unit: "bouquet" },
  { name: "Origan", unit: "c. à café" },
  { name: "Laurier", unit: "feuille" },
  { name: "Piment", unit: "pincée" },
  { name: "Gingembre", unit: "g" },
  { name: "Herbes de Provence", unit: "c. à café" },
  // Fruits
  { name: "Citron", unit: "pièce" },
  { name: "Orange", unit: "pièce" },
  { name: "Pomme", unit: "pièce" },
  { name: "Poire", unit: "pièce" },
  { name: "Banane", unit: "pièce" },
  // Oléagineux & autres
  { name: "Noix", unit: "g" },
  { name: "Amandes", unit: "g" },
  { name: "Noisettes", unit: "g" },
  { name: "Pignons de pin", unit: "g" },
  { name: "Chapelure", unit: "g" },
  { name: "Levure", unit: "sachet" },
];
